
import requests
import json
import os
import sys

def push_to_feishu(content_markdown, webhook_url=None):
    """
    Push markdown content to Feishu via Webhook.
    Does NOT use lark-mcp here to keep the script standalone and schedule-friendly (crontab).
    """
    url = webhook_url or os.environ.get("FEISHU_WEBHOOK_URL")
    if not url:
        print("Error: FEISHU_WEBHOOK_URL is not set.")
        return

    # Construct card message
    card = {
        "msg_type": "interactive",
        "card": {
            "config": {
                "wide_screen_mode": True
            },
            "header": {
                "title": {
                    "tag": "plain_text",
                    "content": "🤖 AI 每日简报"
                },
                "template": "blue"
            },
            "elements": [
                {
                    "tag": "div",
                    "text": {
                        "tag": "lark_md",
                        "content": content_markdown
                    }
                },
                {
                    "tag": "hr"
                },
                {
                    "tag": "note",
                    "elements": [
                        {
                            "tag": "plain_text",
                            "content": "由 Antigravity AI 情报官生成"
                        }
                    ]
                }
            ]
        }
    }

    try:
        response = requests.post(url, json=card)
        response.raise_for_status()
        print("Successfully pushed to Feishu!")
        print(response.json())
    except Exception as e:
        print(f"Failed to push to Feishu: {e}")

if __name__ == "__main__":
    # Read from the file generated by fetch_news.py
    try:
        with open("daily_briefing.md", "r") as f:
            content = f.read()
        
        webhook_url = sys.argv[1] if len(sys.argv) > 1 else None
        push_to_feishu(content, webhook_url)
    except FileNotFoundError:
        print("daily_briefing.md not found. Run fetch_news.py first.")
